### ISSUE TITLE
Support for multiple independant classes

### ISSUE THREAD

**Issue by blindman2k** [electricimp/impTest#29]
I would like to be able to test an entire collection of classes where each class has its own test case set. The project as a whole is too big to add a 15% overhead for the test framework but it would be fine to test one class at a time. This would involve uploading over and over to the same model.

**Comment by myurasov** [comment]
This will be probably TDB for now, as it seems to have some benefits to run test suite on top of entire codebase.

Current recipe is to use separate _.imptest_ configs and use __-c__ key.

With integration of preprocessor there will be more ways of following your scenario.
