### ISSUE TITLE
Security of API keys and other private data

### ISSUE THREAD

**Issue by blindman2k** [electricimp/impTest#30]
Has this been worked out yet?

**Comment by myurasov** [comment]
There are two types of sensitive data impTest tries to protect when a public repo has the test suite:

__Build API key__

If "apiKey" config param is not present, it's read from IMP_BUILD_API_KEY env var. Steps made to protect it:

- It is never exposed in test or init commands output
- Auth header contents is hidden in BuildAPIClient debug output
- Access to #{env:IMP_BUILD_API_KEY} is disallowed in test case
- It's removed from external command environment

__Credentials needed for testing__

- Usage of #{env:VARNAME} syntax allows not to store them in the code
- It's important to understand that if pull request build are enabled on an open repo, access to those cannot be restricted for people who want them

**Comment by myurasov** [comment]
A small update:

Travis CI never allows access to environment variables when builds are initiated from PR created by someone not belonging to organization or outside collaborators on the repository.
